authors:
  hyperdefined:
    name: hyperdefined
    description: I'm hyperdefined, a fluffy, flower wolf. I'm and IT nerd and developer.
    avatar: ../../../assets/img/android-chrome-384x384.png
    url: https://hyper.lol